/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"
#include <stdlib.h>
#include <stdio.h>
#include <time.h>


struct vector
{
	int vec[20];
};

struct vector shiftRight(struct vector x, int count)
{
	struct vector r = x;
	int temp = r.vec[count - 1];

	for (size_t i = 0; i < count - 1; i++)
	{
		/* code */
		r.vec[i + 1] = x.vec[i];
	}

	r.vec[0] = temp;

	return r;
}

struct do_circulant circulant_make(struct do_circulant x)
{
	srand(time(NULL));
	int count = x.size;
	int index = 0;
	struct vector v;
	int matrix[count][count];
	// generate vector.
	printf("preparing circulant matrix \n\n");
	for (size_t i = 0; i < count; i++)
	{
		v.vec[i] = rand() % 10;
	}
	// generate matrix.
	for (size_t i = 0; i < count; i++)
	{
		for (size_t j = 0; j < count; j++)
		{
			matrix[i][j] = v.vec[j];
		}
		// shift elements right.
		v = shiftRight(v, count);
	}

	for (size_t i = 0; i < count; i++)
	{
		for (size_t j = 0; j < count; j++)
		{
			printf("%d	",matrix[i][j]);
		}
		printf("\n");
	}

	//change 2-D array to 1 - D array.

	for (size_t i = 0; i < count; i++)
	{

		for (size_t j = 0; j < count; j++)
		{
			x.matrix[index] = matrix[i][j];
			index++;
		}
	}
	printf("\nfinished \n");
	return x;
}

struct do_circulant *
circulant_1_svc(do_circulant *argp, struct svc_req *rqstp)
{
	static struct do_circulant  result;

	/*
	 * insert server code here
	 */
	result = circulant_make(*argp);

	return &result;
}
