/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _MAIN_H_RPCGEN
#define _MAIN_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct do_circulant {
	int size;
	int matrix[200];
};
typedef struct do_circulant do_circulant;

#define Do_Circulant 0x23451111
#define Do_VERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define circulant 1
extern  struct do_circulant * circulant_1(do_circulant *, CLIENT *);
extern  struct do_circulant * circulant_1_svc(do_circulant *, struct svc_req *);
extern int do_circulant_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define circulant 1
extern  struct do_circulant * circulant_1();
extern  struct do_circulant * circulant_1_svc();
extern int do_circulant_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_do_circulant (XDR *, do_circulant*);

#else /* K&R C */
extern bool_t xdr_do_circulant ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_MAIN_H_RPCGEN */
