/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "main.h"


void
do_circulant_1(char *host, int size)
{
	CLIENT *clnt;
	struct do_circulant  *result_1;
	do_circulant  circulant_1_arg;
	int matrix[size][size];
	int index = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, Do_Circulant, Do_VERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */
	circulant_1_arg.size = size;
	result_1 = circulant_1(&circulant_1_arg, clnt);
	if (result_1 == (struct do_circulant *) NULL) {
		clnt_perror (clnt, "call failed");
	} else{
		// create 2-D array.
		for(size_t i = 0; i < size; i++)
		{
			for(size_t j = 0; j < size; j++)
			{
				matrix[i][j] = result_1->matrix[j + index];
			}
			index = index + size;	
		}
		
		// print the matrix.
		printf("The do circulant matrix of %d element(s): \n",size);
		int count = size * size;
		for(size_t i = 0; i < size; i++)
		{
			
			for(size_t j = 0; j < size; j++)
			{
				printf("%d	", matrix[i][j]);
			}
			printf("\n");
		}
		printf("\n");
	}
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;

	if (argc < 3) {
		printf ("usage: %s server_host vector_size\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	do_circulant_1(host, atoi(argv[2]));
	exit(0);
}
